CREATE TABLE sources(id INTEGER PRIMARY KEY,uri TEXT NOT NULL,kind TEXT NOT NULL,UNIQUE(uri,kind));
CREATE TABLE media_files(id INTEGER PRIMARY KEY,source_id INTEGER NOT NULL REFERENCES sources(id),uri TEXT NOT NULL UNIQUE,relative TEXT NOT NULL,identity TEXT NOT NULL UNIQUE,size INTEGER NOT NULL,modified INTEGER NOT NULL,data TEXT NOT NULL,music INTEGER NOT NULL DEFAULT 0,UNIQUE(source_id,relative));
CREATE TABLE books(id INTEGER PRIMARY KEY,source_id INTEGER NOT NULL UNIQUE REFERENCES sources(id),title TEXT NOT NULL,author TEXT NOT NULL,cover TEXT);
CREATE TABLE book_parts(id INTEGER PRIMARY KEY,book_id INTEGER NOT NULL REFERENCES books(id) ON DELETE CASCADE,file_id INTEGER NOT NULL REFERENCES media_files(id),ordinal INTEGER NOT NULL,title TEXT NOT NULL,UNIQUE(book_id,file_id),UNIQUE(book_id,id));
CREATE TABLE chapters(id INTEGER PRIMARY KEY,part_id INTEGER NOT NULL REFERENCES book_parts(id) ON DELETE CASCADE,title TEXT NOT NULL,start INTEGER NOT NULL,end INTEGER);
CREATE TABLE book_progress(book_id INTEGER PRIMARY KEY REFERENCES books(id) ON DELETE CASCADE,part_id INTEGER NOT NULL,position INTEGER NOT NULL CHECK(position>=0),completed INTEGER NOT NULL,updated INTEGER NOT NULL,FOREIGN KEY(book_id,part_id) REFERENCES book_parts(book_id,id) ON DELETE CASCADE);
CREATE TABLE queue_entries(id INTEGER PRIMARY KEY,file_id INTEGER NOT NULL REFERENCES media_files(id),ordinal INTEGER NOT NULL UNIQUE);
CREATE TABLE session_state(id INTEGER PRIMARY KEY CHECK(id=1),data TEXT NOT NULL);
CREATE INDEX book_parts_order ON book_parts(book_id,ordinal);
